-- Seed property_presets. Slug is the stable handle referenced by event_properties.
-- See tracker/docs/SEED_CATALOG.md for the canonical list.

INSERT INTO property_presets (slug, name, widget, options, is_seed) VALUES
    ('severity-1-5', 'Severity 1–5', 'step',
     '[{"value":1,"label":"Mild"},{"value":2,"label":"Annoying"},{"value":3,"label":"Moderate"},{"value":4,"label":"Severe"},{"value":5,"label":"Migraine"}]'::jsonb,
     true),
    ('face-mood-1-5', 'Mood faces', 'face_select',
     '[{"value":1,"label":"Awful","emoji":"😩"},{"value":2,"label":"Down","emoji":"🙁"},{"value":3,"label":"Meh","emoji":"😐"},{"value":4,"label":"Good","emoji":"🙂"},{"value":5,"label":"Great","emoji":"😄"}]'::jsonb,
     true),
    ('quality-1-5', 'Quality 1–5', 'face_select',
     '[{"value":1,"label":"Poor"},{"value":2,"label":"Fair"},{"value":3,"label":"OK"},{"value":4,"label":"Good"},{"value":5,"label":"Great"}]'::jsonb,
     true),
    ('side-single', 'Side', 'single_select',
     '[{"value":"left","label":"Left"},{"value":"right","label":"Right"},{"value":"both","label":"Both"}]'::jsonb,
     true),
    ('headache-location-multi', 'Headache location', 'multi_select',
     '[{"value":"front","label":"Front"},{"value":"temple","label":"Temple"},{"value":"back","label":"Back"},{"value":"crown","label":"Crown"},{"value":"behind_eyes","label":"Behind eyes"}]'::jsonb,
     true),
    ('body-location-multi', 'Body location', 'multi_select',
     '[{"value":"back","label":"Back"},{"value":"neck","label":"Neck"},{"value":"shoulders","label":"Shoulders"},{"value":"hips","label":"Hips"},{"value":"knees","label":"Knees"},{"value":"other","label":"Other"}]'::jsonb,
     true),
    ('with-food-single', 'With food', 'single_select',
     '[{"value":"none","label":"None"},{"value":"breakfast","label":"Breakfast"},{"value":"lunch","label":"Lunch"},{"value":"dinner","label":"Dinner"},{"value":"empty","label":"Empty stomach"}]'::jsonb,
     true),
    ('meal-type-single', 'Meal type', 'single_select',
     '[{"value":"breakfast","label":"Breakfast"},{"value":"lunch","label":"Lunch"},{"value":"dinner","label":"Dinner"},{"value":"snack","label":"Snack"}]'::jsonb,
     true),
    ('bristol-1-7', 'Bristol scale', 'face_select',
     '[{"value":1,"label":"Hard lumps"},{"value":2,"label":"Lumpy sausage"},{"value":3,"label":"Cracked sausage"},{"value":4,"label":"Smooth sausage"},{"value":5,"label":"Soft blobs"},{"value":6,"label":"Mushy"},{"value":7,"label":"Liquid"}]'::jsonb,
     true),
    ('cough-type-single', 'Cough type', 'single_select',
     '[{"value":"dry","label":"Dry"},{"value":"wet","label":"Wet"}]'::jsonb,
     true),
    ('flow-1-5', 'Flow', 'step',
     '[{"value":1,"label":"None"},{"value":2,"label":"Spotting"},{"value":3,"label":"Light"},{"value":4,"label":"Medium"},{"value":5,"label":"Heavy"}]'::jsonb,
     true),
    ('pms-multi', 'PMS symptoms', 'multi_select',
     '[{"value":"mood","label":"Mood"},{"value":"bloating","label":"Bloating"},{"value":"cravings","label":"Cravings"},{"value":"breast_tender","label":"Breast tender"},{"value":"headache","label":"Headache"},{"value":"cramps","label":"Cramps"}]'::jsonb,
     true),
    ('workout-type-single', 'Workout type', 'single_select',
     '[{"value":"run","label":"Run"},{"value":"lift","label":"Lift"},{"value":"yoga","label":"Yoga"},{"value":"walk","label":"Walk"},{"value":"bike","label":"Bike"},{"value":"swim","label":"Swim"},{"value":"other","label":"Other"}]'::jsonb,
     true),
    ('alcohol-type-single', 'Alcohol type', 'single_select',
     '[{"value":"beer","label":"Beer"},{"value":"wine","label":"Wine"},{"value":"spirits","label":"Spirits"},{"value":"cocktail","label":"Cocktail"}]'::jsonb,
     true),
    ('cannabis-method-single', 'Cannabis method', 'single_select',
     '[{"value":"smoke","label":"Smoke"},{"value":"edible","label":"Edible"},{"value":"vape","label":"Vape"}]'::jsonb,
     true),
    ('bool-yes-no', 'Yes / No', 'bool',
     '{"trueLabel":"Yes","falseLabel":"No"}'::jsonb,
     true),
    ('count', 'Count', 'number',
     '{"min":0,"max":1000,"step":1,"default":1}'::jsonb,
     true),
    ('dose-mg', 'Dose (mg)', 'dose',
     '{"unit":"mg","min":0,"max":2000,"step":50,"default":200}'::jsonb,
     true),
    ('dose-tablets', 'Dose (tablets)', 'dose',
     '{"unit":"tablet","min":0,"max":20,"step":1,"default":1}'::jsonb,
     true),
    ('dose-glasses', 'Glasses', 'dose',
     '{"unit":"glass","min":0,"max":30,"step":1,"default":1}'::jsonb,
     true),
    ('dose-cups', 'Cups', 'dose',
     '{"unit":"cup","min":0,"max":20,"step":1,"default":1}'::jsonb,
     true),
    ('duration-minutes', 'Duration (minutes)', 'duration',
     '{"unit":"minutes","min":0,"max":600,"step":5,"default":30}'::jsonb,
     true),
    ('duration-hours', 'Duration (hours)', 'duration',
     '{"unit":"hours","min":0,"max":24,"step":0.25,"default":7}'::jsonb,
     true),
    ('temperature-c', 'Temperature (°C)', 'number',
     '{"unit":"°C","min":34,"max":42,"step":0.1,"default":37}'::jsonb,
     true),
    ('text-short', 'Short text', 'text',
     '{"placeholder":"","maxLength":280}'::jsonb,
     true),
    ('text-long', 'Long text', 'text',
     '{"placeholder":"What''s on your mind?","maxLength":5000}'::jsonb,
     true);
