services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./beer:/var/www/html/beer
      - /var/lib/docker/volumes/apps/beer:/var/www/data/beer
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
    extra_hosts:
      - "host.docker.internal:host-gateway"
